const assert = require('node:assert/strict');
const data = require('../gym_tracker/data.js');
assert.equal(data.number(''), null);
assert.equal(data.number('  '), null);
assert.equal(data.number('0'), 0);
assert.equal(data.number('Infinity'), null);
assert.equal(data.inWindow('2026-09-16', 7, new Date(2026, 8, 16)), true);
assert.equal(data.inWindow('2026-09-10', 7, new Date(2026, 8, 16)), true);
assert.equal(data.inWindow('2026-09-09', 7, new Date(2026, 8, 16)), false);
assert.equal(data.inWindow('2026-09-17', 7, new Date(2026, 8, 16)), false);
assert.equal(data.validDate('2026-02-30'), false);
const base = { workouts: [], meals: [], metrics: [] };
assert.deepEqual(data.normalize(base).exercises, []);
assert.throws(() => data.normalize({ workouts: 'bad' }));
assert.throws(() => data.normalize({ ...base, meals: [{ date: '2026-09-16', food: '', meal: 'Lunch', calories: -1, protein: 1, carbs: 1, fat: 1 }] }));
const merged = data.normalize({ ...base, metrics: [{ date: '2026-09-16', bodyweight: 180, sleepHours: null }, { date: '2026-09-16', bodyweight: null, sleepHours: 8 }] });
assert.equal(merged.metrics.length, 1);
assert.equal(merged.metrics[0].bodyweight, 180);
assert.equal(merged.metrics[0].sleepHours, 8);
assert.equal(data.normalize({ ...base, workouts: [{ date: '2026-09-16', exercise: 'Squat', weight: 100, reps: 5, setNumber: 1, rpe: 0 }] }).workouts[0].rpe, null);
console.log('Data regression checks passed.');
